name: CI

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  test-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          tags: cheald/sentry-mattermost-integration:test-build-ci
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  pre-release:
    name: "Pre Release"
    if: ${{ github.repository == 'cheald/sentry-mattermost-integration' && contains(github.ref, 'refs/heads/master') }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: cheald/sentry-mattermost-integration:latest
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"

  tagged-release:
    name: "Tagged Release"
    if: ${{ github.repository == 'cheald/sentry-mattermost-integration' && contains(github.ref, 'refs/tags/v') }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Generate version variable
        id: branch_name
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: cheald/sentry-mattermost-sidecar:${{ steps.branch_name.outputs.TAG_VERSION }}
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
